# Dockerfile.dev
FROM node:20-alpine

WORKDIR /home/app

COPY package*.json ./

RUN npm install

COPY . .

# Generate Prisma client
RUN npx prisma generate

EXPOSE 5000

CMD npx prisma db push && npm run dev